import {
    Archive,
    HandCoins,
    ClipboardCheck,
    ArrowLeftRight,
    BarChart3,
    BookOpen,
    CalendarCheck,
    CalendarDays,
    CalendarRange,
    Church,
    Droplets,
    Clock,
    ClipboardList,
    Eye,
    FolderLock,
    HandHeart,
    Image,
    KeyRound,
    Layers,
    LayoutDashboard,
    Megaphone,
    MessagesSquare,
    Network,
    Package,
    Boxes,
    Bus,
    PartyPopper,
    Handshake,
    Landmark,
    RadioTower,
    Route,
    Scale,
    Settings,
    ShieldCheck,
    Smartphone,
    Sparkles,
    User,
    UserCheck,
    UserCog,
    Users,
    UsersRound,
    Wallet,
    X,
    AlertTriangle,
    CircleHelp,
    History,
    LogOut,
    Pencil,
    Plus,
    Search,
    TrendingDown,
    UserPlus,
    UserX,
    AtSign,
    BookMarked,
    CalendarClock,
    CircleUser,
    FileText,
    Hash,
    Home,
    IdCard,
    MapPin,
    Phone,
    Quote,
    Tag,
    Type,
    Venus,
    Download,
    Receipt,
    TrendingUp,
    ShieldAlert,
    GraduationCap,
    Building2,
    Inbox,
    ScrollText,
    Tags,
} from 'lucide-vue-next';

/**
 * LE PONT ENTRE LE CATALOGUE PHP ET LES ICÔNES VUE.
 *
 * `App\Metier\Acces\Modules` nomme une icône Lucide par module, en kebab-case. Le catalogue est du
 * PHP : il ne peut pas envoyer un composant Vue, seulement son nom. Cette table fait la
 * correspondance.
 *
 * Les imports sont EXPLICITES, un par icône. On pourrait importer tout Lucide et résoudre le nom à
 * l'exécution — mais le paquet compte plus de mille icônes, et aucune ne serait éliminée à la
 * compilation. Ici, ce qui n'est pas listé n'est pas embarqué.
 */
const ICONES = {
    // La console de l'éditeur.
    'building-2': Building2,
    inbox: Inbox,
    'scroll-text': ScrollText,
    tags: Tags,
    'arrow-left-right': ArrowLeftRight,
    'bar-chart-3': BarChart3,
    'book-open': BookOpen,
    'calendar-check': CalendarCheck,
    'calendar-days': CalendarDays,
    'calendar-range': CalendarRange,
    church: Church,
    droplets: Droplets,
    'clipboard-list': ClipboardList,
    eye: Eye,
    'folder-lock': FolderLock,
    'hand-heart': HandHeart,
    'hand-coins': HandCoins,
    'clipboard-check': ClipboardCheck,
    image: Image,
    layers: Layers,
    'layout-dashboard': LayoutDashboard,
    archive: Archive,
    megaphone: Megaphone,
    'messages-square': MessagesSquare,
    network: Network,
    package: Package,
    boxes: Boxes,
    bus: Bus,
    'party-popper': PartyPopper,
    handshake: Handshake,
    landmark: Landmark,
    'radio-tower': RadioTower,
    route: Route,
    scale: Scale,
    settings: Settings,
    'shield-check': ShieldCheck,
    smartphone: Smartphone,
    sparkles: Sparkles,
    user: User,
    'user-check': UserCheck,
    'user-cog': UserCog,
    users: Users,
    'users-round': UsersRound,
    wallet: Wallet,
    clock: Clock,
    venus: Venus,
    type: Type,
    tag: Tag,
    quote: Quote,
    phone: Phone,
    'map-pin': MapPin,
    'id-card': IdCard,
    home: Home,
    hash: Hash,
    'file-text': FileText,
    'circle-user': CircleUser,
    'calendar-clock': CalendarClock,
    'book-marked': BookMarked,
    'at-sign': AtSign,
    'user-x': UserX,
    'user-plus': UserPlus,
    'trending-down': TrendingDown,
    search: Search,
    plus: Plus,
    pencil: Pencil,
    'log-out': LogOut,
    history: History,
    'circle-help': CircleHelp,
    'alert-triangle': AlertTriangle,
    x: X,
    'key-round': KeyRound,
    download: Download,
    receipt: Receipt,
    'trending-up': TrendingUp,
    'shield-alert': ShieldAlert,
    'graduation-cap': GraduationCap,
};

/**
 * L'icône d'un nom Lucide, ou une icône de repli.
 *
 * Le repli compte : si le catalogue gagne un module dont l'icône n'est pas encore listée ici,
 * l'entrée de menu doit rester lisible. Sans lui, `<component :is="undefined">` ferait disparaître
 * l'entrée sans la moindre erreur — exactement le genre de panne silencieuse qu'on cherche à
 * éviter.
 */
export function icone(nom) {
    return ICONES[nom] ?? Layers;
}

export { LayoutDashboard };
